In [2]:
import tensorflow as tf

In [3]:
string = tf.Variable("this is a string", tf.string)
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567, tf.float64)

In [4]:
print(string)
print(number)
print(floating)

<tf.Variable 'Variable:0' shape=() dtype=string, numpy=b'this is a string'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=324>
<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.567>


Rank/Degree of Tensor 
Another word for rank is degree, these terms simply mean the number of dimensions involved in the tensor. What we created above is a thensor of rank 0, also know as a scalar.
now we'll create some tensors of higher degrees/rank

In [5]:
rank1_tensor = tf.Variable(["test"], tf.string)
rank2_tensor = tf.Variable([["test", "ok"], ["test","yes"]], tf.string)

In [6]:
tf.rank(rank2_tensor)


<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [7]:
rank2_tensor.shape

TensorShape([2, 2])

Changin shapes 
The number of elements of a tensor is the product os the sizes of all its shapes. There are often many shapes that have the same number of elements, making it convenient to be able to change the shape if a tensor

In [28]:
tensor1 = tf.zeros([1,2,3]) #tf.ones() creates a shape [1,2,3] tensor fill of ones
tensor2 = tf.reshape(tensor1, [2,3,1]) #reshape existing data to shape [2,3,1]
tensor3 = tf.reshape(tensor2, [3, -1])
# -1 telles the tensor to calculate the size of the dimension in that place, this will reshape the tensor to [3,3] The number of elements in #the reshaped tensor MUST match the # #number in the original.


In [29]:
print(tensor1)
print(tensor2)
print(tensor3)

tf.Tensor(
[[[0. 0. 0.]
  [0. 0. 0.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[0.]
  [0.]
  [0.]]

 [[0.]
  [0.]
  [0.]]], shape=(2, 3, 1), dtype=float32)
tf.Tensor(
[[0. 0.]
 [0. 0.]
 [0. 0.]], shape=(3, 2), dtype=float32)


Before we go to far I will mention that there are different types of tensors. These are the most commonly used and we will talk more in depth about each as they are used.
 - Variable
 - Constant
 - Placegikder
 - SparseTensor
With the exeption of Variable all of these tensors are immuttable, meaning their value may not change during execution.

